# Generated by Django 4.2.15 on 2024-08-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('topWords', models.JSONField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
